import type { StoredAnalysis, Hypothesis } from "./schemas";

function badge(level: string) {
  const map: Record<string, string> = {
    high: "🔴 High",
    medium: "🟡 Medium",
    low: "🟢 Low",
  };
  return map[level] ?? level;
}

export function exportAnalysisToMarkdown(analysis: StoredAnalysis): string {
  const { url, ai_analysis, extracted_data, created_at } = analysis;
  const { overall_score, summary, hypotheses } = ai_analysis;

  const lines: string[] = [
    `# CRO Hypothesis Backlog`,
    ``,
    `**URL:** ${url}`,
    `**Analyzed:** ${new Date(created_at).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}`,
    `**Overall CRO Score:** ${overall_score}/100`,
    ``,
    `## Summary`,
    ``,
    summary,
    ``,
    `## Page Snapshot`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Title | ${extracted_data.title || "—"} |`,
    `| H1 | ${extracted_data.h1[0] || "—"} |`,
    `| CTA Count | ${extracted_data.cta_count} |`,
    `| Word Count | ${extracted_data.word_count} |`,
    `| Risk Reducers | ${extracted_data.risk_reducers.join(", ") || "None"} |`,
    `| Trust Indicators | ${extracted_data.trust_indicators.join(", ") || "None"} |`,
    ``,
    `## Hypotheses (${hypotheses.length})`,
    ``,
  ];

  hypotheses.forEach((h: Hypothesis, i: number) => {
    lines.push(
      `### #${i + 1} — ${h.title}`,
      ``,
      `| | |`,
      `|---|---|`,
      `| **Area** | ${h.area} |`,
      `| **ICE Score** | ${h.ice_score}/10 |`,
      `| **Impact** | ${badge(h.expected_impact)} |`,
      `| **Confidence** | ${badge(h.confidence)} |`,
      `| **Effort** | ${badge(h.effort)} |`,
      `| **Page Element** | ${h.affected_page_element} |`,
      ``,
      `**Observed Issue:** ${h.observed_issue}`,
      ``,
      `**Hypothesis:** ${h.hypothesis}`,
      ``,
      `**Why It Matters:** ${h.why_it_matters}`,
      ``,
      `**Recommended Test:** ${h.recommended_test}`,
      ``
    );

    if (h.example_variant_copy) {
      lines.push(
        `**Example Variant Copy:**`,
        `> ${h.example_variant_copy}`,
        ``
      );
    }

    lines.push(
      `**Evidence from Page:** ${h.evidence_from_page}`,
      ``,
      `---`,
      ``
    );
  });

  lines.push(
    `*Generated by CRO Hypothesis Generator*`
  );

  return lines.join("\n");
}
